CREATE TABLE public.conveniado (
	seq_conveniado int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome text NULL,
	nome_fantasaia text NULL,
	email text NULL,
	cnpj text NULL,
	atividade text NULL,
	data_registro date NULL,
	telefone text NULL,
	celular text NULL,
	nome_responsavel text NULL,
	nome_endereco text NULL,
	bairro text NULL,
	cidade text NULL,
	uf text NULL,
	cep text NULL,
	coordenadas point NULL
);